// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cfzdgtxezizejxvbzpwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmemRndHhleml6ZWp4dmJ6cHdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NTY5NDAsImV4cCI6MjA2NDMzMjk0MH0.AebKb-K9la3L5UpTyew1CSFaX-msjgvNZVUwibnlV9w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);